# Generated by Django 5.1.3 on 2024-11-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='whatsapp',
            field=models.IntegerField(null=True),
        ),
    ]
