# Generated by Django 5.1.3 on 2024-11-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_company_email_alter_company_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('description', models.CharField(max_length=5000)),
                ('location', models.CharField(max_length=500)),
                ('jobtype', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract')], default='Full Time', max_length=1000)),
                ('hours', models.IntegerField()),
                ('days', models.IntegerField()),
                ('minsalary', models.IntegerField()),
                ('maxsalary', models.IntegerField()),
                ('qualification', models.CharField(max_length=500)),
                ('skills', models.CharField(max_length=500)),
                ('experience', models.IntegerField()),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Other', max_length=1000)),
                ('minage', models.IntegerField(null=True)),
                ('maxage', models.IntegerField(null=True)),
                ('approval', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=1000)),
            ],
        ),
    ]
