# Generated by Django 5.1.3 on 2024-11-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
