# Generated by Django 5.1.3 on 2024-11-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_usersignup_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='maxsalary',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='minsalary',
            field=models.CharField(max_length=15),
        ),
    ]
