# Generated by Django 5.1.3 on 2024-11-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_company_phone_alter_job_maxsalary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='whatsapp',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
