# Generated by Django 5.1.3 on 2024-11-12 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_company_whatsapp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='job',
        ),
    ]
