# Generated by Django 5.1.3 on 2024-11-12 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='companyname',
        ),
        migrations.DeleteModel(
            name='company',
        ),
        migrations.DeleteModel(
            name='job',
        ),
    ]
